### ISSUE TITLE
Activation of Localization and Bluetooth via App

### ISSUE THREAD

**Issue by Beardmix** [Beardmix/CriticalMass_SmartBike#10]
Offer the possibility to activate localization and bluetooth in the app. (link to options if not possible directly)
Check the status of the localization and the bluetooth in the app and display a warning if they are not activated.

**Comment by OnizukaX** [comment]
https://forum.ionicframework.com/t/how-to-check-if-geolocation-is-enable-or-not-with-native-gps/88762/4
