### ISSUE TITLE
Peripheral crashes when disconnected from Master

### ISSUE THREAD

**Issue by OnizukaX** [Beardmix/CriticalMass_SmartBike#12]
When the Master disconnects from the Peripherals, Peripherals might crash. Rootcause unknown.

**Comment by OnizukaX** [comment]
After some testing, this seems to have to do with the Adafruit_NeoPixel library.
Having the strip.show() calls commented out keeps the Peripheral working when disconnected from Central: are interrupts responsible?

**Comment by OnizukaX** [comment]
Refering to the task scheduler section of the nRF52 doc: https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/faqs#faq-5
> How are Arduino sketches executed on the nRF52832? Can I do hard real time processing (bit-banging NeoPixels, etc.)?
In order to run Arduino code on the nRF52 at the same time as the low level Bluetooth Low Energy stack, the Bluefruit nRF52 Feather uses FreeRTOS as a task scheduler. The scheduler will automatically switch between tasks, assigning clock cycles to the highest priority task at a given moment. This process is generally transparent to you, although it can have implications if you have hard real time requirements. There is no guarantee on the nRF52832 to meet hard timing requirements when the radio is enabled an being actively used for Bluetooth Low Energy. This isn't possible on the nRF52832 even without FreeRTOS, though, since the SoftDevice (Nordic's propietary binary blob stack) has higher priority than any user code, including control over interrupt handlers.

Refering to the FreeRTOS hook functions: https://www.freertos.org/a00016.html

So far no hooks seems to handle this unknown issue.

**Comment by OnizukaX** [comment]
Problem still occuring with Adafruit nrf52 Arduino Core 0.8.6.

Somehow almost no crash seem to happen when compiling with:
**Debug Mode: "Level 3 (Segger SystemView)"**.

**Comment by wwwoholic** [comment]
Still occurring with 0.9.0
I noticed that it is easier to trigger this error if nodes are actively exchanging data (100~300 Bps) and one of the nodes is simply rebooted.

**Comment by OnizukaX** [comment]
Solved in v1.1.8 - https://github.com/adafruit/Adafruit_NeoPixel/releases/tag/1.1.8
