### ISSUE TITLE
Automode

### ISSUE THREAD

**Issue by Beardmix** [Beardmix/CriticalMass_SmartBike#13]
Create a mode that changes the effects in a random manner to avoid having to change every minute

**Comment by Beardmix** [comment]
A first working version can be found here:
f335c96 in branch #13_automode

The color is kept as chosen by the user. 

should the color change automatically? if yes, through a defined set or random?

**Comment by artur-braga** [comment]
Branch closed and merged in commit : 96469f3075fe16817fb949a5e67d79893862c63a
