### ISSUE TITLE
Checksum for robustness

### ISSUE THREAD

**Issue by Beardmix** [Beardmix/CriticalMass_SmartBike#3]
A checksum should be implemented for checking the validity of the packets sent.

This could be done in a simple way first and enhanced later.

1. Simple checksum and discard of erroneous packets.
2. Simple checksum and asking the packets again when erroneous (with a max number of calls?).
3. More advanced checksum if needed.

**Comment by OnizukaX** [comment]
CRC already implemented in Nordic firmware.
https://devzone.nordicsemi.com/f/nordic-q-a/16196/do-i-need-checksum-to-ensure-my-data-is-intact
