### ISSUE TITLE
Crash every time the parameters are saved manually

### ISSUE THREAD

**Issue by Beardmix** [Beardmix/CriticalMass_SmartBike#31]
Every time the parameters are saved, the device crashes while saving, saving only a part of the parameters, and preventing further savings.
The first saving works (the one automatic after reflashing the ROM)

The error code is 2, which is define in fs.h as:
`#define FS_EHW          2  /* Error accessing storage medium */`
[https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/nffs/src/fs/fs/include/fs/fs.h]

usually, the error was `#define FS_EOFFSET      3  /* Invalid offset */`, which was more cryptic and happened while the device was not crashing.

It is probably due to BLE interrupts, or size of parameters to save?

Full log here:

```
--- Peripheral---

File /settings.txt not found.
--------- SoftDevice Config ---------
Max UUID128     : 10
ATTR Table Size : 2048
Service Changed : 0
Peripheral Connect Setting
  - Max MTU         : 23
  - Event Length    : 3
  - HVN Queue Size  : 1
  - WrCmd Queue Size: 1

--------- BLE Settings ---------
Name            : Bluefruit52
Max Connections : Peripheral = 1, Central = 0 
Address         : D9:EF:3D:CA:77:49 (Static)
TX Power        : 0 dBm
Conn Intervals  : min = 20.00 ms, max = 30.00 ms
Peripheral Paired Devices: 

Central Paired Devices: 


startAdv
+++ Connected +++
Pixel 2
payload sent #T60!
payload sent #C255,128,0!
payload sent #M8!
[SETTINGS] request cfg, will send chunk#1
payload sent #D1;50;0;MyFahrrad!
[SETTINGS] request cfg, will send chunk#2
payload sent #D2;1;11;38;50!
[SETTINGS] request cfg done.
[SETTINGS] ready to get cfg chunk#1
payload sent #DA!
[SETTINGS] getting cfg chunk#1 ask for chunk#2
0
payload sent #DB!
[SETTINGS] getting chunk#2
Open /settings.txt file to write ... 
Writting Setting: num_pixels=50;
Writting Setting: strip_rev=0;
Writting Setting: d_name=MyFahrrad;
Writting Setting: traffic_fl=1;
Writting Setting: traffic_fu=11;
Writting Setting: traffic_rl=38;
Writting Setting: traffic_ru=50;
payload sent #S801!
payload sent #S170!
payload sent #S390!
payload sent #S950!
payload sent #S280!
payload sent #S870!
payload sent #S001!
[SETTINGS] ready to get cfg chunk#1
payload sent #DA!
[SETTINGS] getting cfg chunk#1 ask for chunk#2
1
payload sent #DB!
[SETTINGS] getting chunk#2
Open /settings.txt file to write ... 
Writting Setting: num_pixels=50;
Writting Setting: strip_rev=1;
Writting Setting: d_name=Sophie;
Writting Setting: traffic_fl=42;
Error - len_written: 0 | file.errnum: 2
Writting Setting: traffic_fu=50;

```

**Comment by Beardmix** [comment]
Complement:
This is the content of the ROM after a saving failure:

```
root
|_ adafruit/
|  |_ bond/
|_ lost+found/
|_ settings.txt                                    98 Bytes

```

Nothing is suspicious.. 


Erasing the ROM as in the example is not possible when integrated in the code (see issue on Adafruit Repo). Erasing fails after one sector successfully erased, and the file cannot be written afterwards, even if it doesn't trigger any error!

**Comment by OnizukaX** [comment]
Seems to be resolved with all the latest file system changes.
 [Adafruit nRF52 v0.11.0](https://github.com/adafruit/Adafruit_nRF52_Arduino/releases/tag/0.11.0) looks fine.
